[phases.setup]
aptPkgs = [
  "libgl1",
  "libglx-mesa0",
  "libglib2.0-0",
  "libsm6",
  "libxext6",
  "libxrender1",
  "libgomp1",
  "ffmpeg"
]
nixPkgs = [
  "libGL",
  "glib",
  "freeglut",
  "zlib"
]

[variables]
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/lib64:$LD_LIBRARY_PATH"

[start]
cmd = "uvicorn Backend.app:app --host 0.0.0.0 --port ${PORT:-8080}"
